services:
  # This is your Spring Boot application
  - type: web
    name: fintracker-api
    runtime: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/financial-tracker-api-3.5.5.jar"
    envVars:
      - key: DB_URL # This will be the full JDBC URL for PostgreSQL
        fromDatabase:
          name: fintracker-db
          property: connectionString
      - key: JWT_SECRET
        sync: false # You will set this manually in the Render dashboard for security

  # This is your PostgreSQL database
  - type: pserv
    name: fintracker-db
    plan: free